import { Router } from "express";
import { getGeminiClient } from "../server";

const router = Router();

async function generateSocialPlan(vibe: string, category: string) {
  if (!vibe) {
    throw new Error("Please provide a vibe description for the plan!");
  }

  const client = getGeminiClient();
  const systemInstruction = 
    `You are the Planless AI Social Coordinator.\n` +
    `Planless is a social productivity and spontaneous coordination app for young friends, campus circles, and cohorts.\n` +
    `The app values lightweight social interactions, Spotify-style calmness, and real-life connections.\n\n` +
    `Generate a highly compelling, specific, and realistic spontaneous social plan matching the user's vibe: "${vibe}" and preferred category: "${category || 'any'}".\n\n` +
    `The output must be a valid raw JSON object matching this TypeScript format exactly, with NO markdown block wrappers (no \`\`\`json or \`\`\` text): \n` +
    `{\n` +
    `  "title": "Compelling Title (under 30 chars, e.g., '🍿 Cinema Crew', '⚽ Rain Turf Football', '🍹 Rooftop Sundowner')",\n` +
    `  "category": "movies" (for cinema, Netflix) | "sports" (for matches, gym) | "restaurants" (for dinner, cafes, drinks) | "custom" (for roadtrips, games, etc.),\n` +
    `  "date": "Today" | "Tomorrow" | "Weekend",\n` +
    `  "time": "e.g., 7:00 PM, 3:30 PM, 9:00 PM",\n` +
    `  "location": "A relatable venue (e.g., 'Skyline Arena Turf', 'Social Cafe', 'Sunset Glassbox Lounge', 'Regal Cinema')",\n` +
    `  "cost": number (estimated split amount in Rupees, e.g. 150, 450, 0),\n` +
    `  "maxSpots": number (sensible spots, e.g., 6, 12, 16),\n` +
    `  "description": "Short social description (under 120 chars) inviting friends and setting the warm positive vibe",\n` +
    `  "notes": "Cozy side-comment or preparation item (under 80 chars, e.g., 'Bring light jackets. We will grab snacks!')"\n` +
    `}`;

  const response = await client.models.generateContent({
    model: "gemini-3.5-flash",
    contents: vibe,
    config: {
      systemInstruction: systemInstruction,
      responseMimeType: "application/json",
      temperature: 0.8,
    },
  });

  const responseText = response.text ? response.text.trim() : "";
  if (!responseText) {
    throw new Error("Empty response generated by Gemini model.");
  }

  return JSON.parse(responseText);
}

// Endpoint supporting body key "vibe" / "/api/generate-plan" legacy
router.post("/generate-plan", async (req, res) => {
  try {
    const { vibe, category } = req.body;
    const planData = await generateSocialPlan(vibe, category);
    res.json(planData);
  } catch (error: any) {
    console.error("AI Generation Error:", error);
    res.status(500).json({ error: error.message || "Failed to generate social plan." });
  }
});

// Endpoint supporting body key "prompt" / "/api/ai/coordinate" MVP flow
router.post("/coordinate", async (req, res) => {
  try {
    const { prompt, category } = req.body;
    const planData = await generateSocialPlan(prompt, category);
    res.json(planData);
  } catch (error: any) {
    console.error("AI Generation Error:", error);
    res.status(500).json({ error: error.message || "Failed to generate social plan." });
  }
});

export default router;
